# Generated by Django 3.1.3 on 2021-10-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('cType', models.TextField(blank=True)),
                ('value', models.TextField(blank=True)),
                ('unit', models.TextField(blank=True)),
            ],
        ),
    ]
