# Generated by Django 3.1.3 on 2021-11-09 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_auto_20211109_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='user',
            new_name='owner',
        ),
    ]
